#!/bin/bash


# error precaution.
set -e

WORK_DIR="bot"
mkdir -p $WORK_DIR

disp () {
    echo "-----> $*"
}

indent () {
    sed -u 's/^/       /'
}

_done () {
    echo -e "Done\n" | indent
}

_displaylogo () {
    echo '
===========================================

  ▄████  ██▓███   ▄▄▄       ▄████▄   ██ ▄█▀
 ██▒ ▀█▒▓██░  ██▒▒████▄    ▒██▀ ▀█   ██▄█▒ 
▒██░▄▄▄░▓██░ ██▓▒▒██  ▀█▄  ▒▓█    ▄ ▓███▄░ 
░▓█  ██▓▒██▄█▓▒ ▒░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄ 
░▒▓███▀▒▒██▒ ░  ░ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄
 ░▒   ▒ ▒▓▒░ ░  ░ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒
  ░   ░ ░▒ ░       ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░
░ ░   ░ ░░         ░   ▒   ░        ░ ░░ ░ 
      ░                ░  ░░ ░      ░  ░   
                           ░               
===========================================
|            VERSION  v0.1.0              |
|            By: @Kakashi_HTK             |
|           (C) 2021 - USERGE-X           |
===========================================
'
}

get_branch () {
    local branch
    if [[ $PREF_BRANCH ]]
    then
        branch=$(echo $PREF_BRANCH | xargs)
    else
        branch=main
    fi
    echo "/archive/refs/heads/$branch.zip"
}

get_ziplink () {
    echo "https://github.com/ashwinstr/sedex$(get_branch)"
}

_setup_repo () {
    local zippath
    zippath="$WORK_DIR/temp.zip"
    disp "Fetching Update from Upstream Repo"
    wget -qq $(get_ziplink) -O "$zippath"
    _done
    disp "Unpacking Data"
    unzip -qq "$zippath" -d "$WORK_DIR"
    _done
    disp "Cleaning"
    rm -rf "$zippath"
    _done
}

_startbot () {
    local bot_dir
    bot_dir=$(cd $WORK_DIR && ls) && mv "$WORK_DIR/$bot_dir" "sedex"
    rm -rf $WORK_DIR
    cd "sedex"
    git init > /dev/null 2>&1
    echo -e ">><< --- >><<  Starting [sedex]  >><< --- >><<\n" | indent
    python -m jutsu
}

begin_x () {
    _displaylogo
    sleep 5
    _setup_repo
    _startbot
}

begin_x
