#!/bin/bash


# error precaution.
set -e

WORK_DIR="bot"
mkdir -p $WORK_DIR

disp () {
    echo "-----> $*"
}

indent () {
    sed -u 's/^/       /'
}

_done () {
    echo -e "Done\n" | indent
}

_displaylogo () {
    echo '
===========================================
                                                                                                                                                                                                                        
                                                           bbbbbbbb                                                    
UUUUUUUU     UUUUUUUUXXXXXXX       XXXXXXX                 b::::::b                                      tttt          
U::::::U     U::::::UX:::::X       X:::::X                 b::::::b                                   ttt:::t          
U::::::U     U::::::UX:::::X       X:::::X                 b::::::b                                   t:::::t          
UU:::::U     U:::::UUX::::::X     X::::::X                  b:::::b                                   t:::::t          
 U:::::U     U:::::U XXX:::::X   X:::::XXX                  b:::::bbbbbbbbb       ooooooooooo   ttttttt:::::ttttttt    
 U:::::D     D:::::U    X:::::X X:::::X                     b::::::::::::::bb   oo:::::::::::oo t:::::::::::::::::t    
 U:::::D     D:::::U     X:::::X:::::X                      b::::::::::::::::b o:::::::::::::::ot:::::::::::::::::t    
 U:::::D     D:::::U      X:::::::::X      ---------------  b:::::bbbbb:::::::bo:::::ooooo:::::otttttt:::::::tttttt    
 U:::::D     D:::::U      X:::::::::X      -:::::::::::::-  b:::::b    b::::::bo::::o     o::::o      t:::::t          
 U:::::D     D:::::U     X:::::X:::::X     ---------------  b:::::b     b:::::bo::::o     o::::o      t:::::t          
 U:::::D     D:::::U    X:::::X X:::::X                     b:::::b     b:::::bo::::o     o::::o      t:::::t          
 U::::::U   U::::::U XXX:::::X   X:::::XXX                  b:::::b     b:::::bo::::o     o::::o      t:::::t    tttttt
 U:::::::UUU:::::::U X::::::X     X::::::X                  b:::::bbbbbb::::::bo:::::ooooo:::::o      t::::::tttt:::::t
  UU:::::::::::::UU  X:::::X       X:::::X                  b::::::::::::::::b o:::::::::::::::o      tt::::::::::::::t
    UU:::::::::UU    X:::::X       X:::::X                  b:::::::::::::::b   oo:::::::::::oo         tt:::::::::::tt
      UUUUUUUUU      XXXXXXX       XXXXXXX                  bbbbbbbbbbbbbbbb      ooooooooooo             ttttttttttt  
                                                                                                 
===========================================
|            VERSION  v0.1.0              |
|            By: @Kakashi_HTK             |
|           (C) 2021 - UX-bot             |
===========================================
'
}

get_branch () {
    local branch
    if [[ $PREF_BRANCH ]]
    then
        branch=$(echo $PREF_BRANCH | xargs)
    else
        branch=main
    fi
    echo "/archive/refs/heads/$branch.zip"
}

get_ziplink () {
    echo "https://github.com/ashwinstr/UX-bot$(get_branch)"
}

_setup_repo () {
    local zippath
    zippath="$WORK_DIR/temp.zip"
    disp "Fetching Update from Upstream Repo"
    wget -qq $(get_ziplink) -O "$zippath"
    _done
    disp "Unpacking Data"
    unzip -qq "$zippath" -d "$WORK_DIR"
    _done
    disp "Cleaning"
    rm -rf "$zippath"
    _done
}

_startbot () {
    local bot_dir
    bot_dir=$(cd $WORK_DIR && ls) && mv "$WORK_DIR/$bot_dir" "UX-bot"
    rm -rf $WORK_DIR
    cd "UX-bot"
    git init > /dev/null 2>&1
    echo -e ">><< --- >><<  Starting [UX-bot]  >><< --- >><<\n" | indent
    python -m jutsu
}

begin_x () {
    _displaylogo
    sleep 5
    _setup_repo
    _startbot
}

begin_x
